"""freight rules

Revision ID: 22f2947af244
Revises: bafc7b2e3678
Create Date: 2026-09-29 11:31:33.946761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f2947af244'
down_revision: Union[str, Sequence[str], None] = 'bafc7b2e3678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_rules',
    sa.Column('origin_pin', sa.String(length=6), nullable=False),
    sa.Column('origin_label', sa.String(length=64), nullable=False),
    sa.Column('destination_pin', sa.String(length=6), nullable=False),
    sa.Column('destination_label', sa.String(length=64), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate_unit', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_freight', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('INR', 'USD')", name=op.f('ck_freight_rules_currency')),
    sa.CheckConstraint("destination_pin ~ '^[1-9][0-9]{5}$'", name=op.f('ck_freight_rules_destination_pin')),
    sa.CheckConstraint("origin_pin ~ '^[1-9][0-9]{5}$'", name=op.f('ck_freight_rules_origin_pin')),
    sa.CheckConstraint("rate_unit = 'KG'", name=op.f('ck_freight_rules_rate_unit')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_freight_rules_effective_range')),
    sa.CheckConstraint('minimum_freight IS NULL OR minimum_freight >= 0', name=op.f('ck_freight_rules_minimum_freight_non_negative')),
    sa.CheckConstraint('rate_per_kg > 0', name=op.f('ck_freight_rules_rate_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freight_rules'))
    )
    op.create_index(op.f('ix_freight_rules_destination_pin'), 'freight_rules', ['destination_pin'], unique=False)
    op.create_index(op.f('ix_freight_rules_origin_pin'), 'freight_rules', ['origin_pin'], unique=False)
    op.add_column('organisations', sa.Column('dispatch_pin', sa.String(length=6), nullable=True))
    op.add_column('organisations', sa.Column('dispatch_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO permissions (id, code, description) VALUES "
        "(gen_random_uuid(), 'freight.manage', 'Create and maintain SourceOne freight rules')"
    )
    for role in ("platform_admin", "pricing_admin"):
        op.execute(
            "INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p WHERE r.code = '{role}' AND p.code = 'freight.manage'"
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = 'freight.manage')")
    op.execute("DELETE FROM permissions WHERE code = 'freight.manage'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'dispatch_label')
    op.drop_column('organisations', 'dispatch_pin')
    op.drop_index(op.f('ix_freight_rules_origin_pin'), table_name='freight_rules')
    op.drop_index(op.f('ix_freight_rules_destination_pin'), table_name='freight_rules')
    op.drop_table('freight_rules')
    # ### end Alembic commands ###
