"""erp read only integration v1

Revision ID: 3c741306f4ca
Revises: 720924656e23
Create Date: 2026-09-29 10:36:38.376803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c741306f4ca'
down_revision: Union[str, Sequence[str], None] = '720924656e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_sync_runs',
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_sys_date', sa.DateTime(), nullable=True),
    sa.Column('snapshot_as_of_date', sa.Date(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('succeeded')", name=op.f('ck_erp_sync_runs_status')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_erp_sync_runs_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_erp_sync_runs_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_sync_runs'))
    )
    op.create_table('erp_customers',
    sa.Column('erp_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("gstin IS NULL OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'", name=op.f('ck_erp_customers_gstin_format')),
    sa.CheckConstraint("pin_code IS NULL OR pin_code ~ '^[1-9][0-9]{5}$'", name=op.f('ck_erp_customers_pin_format')),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['erp_sync_runs.id'], name=op.f('fk_erp_customers_last_sync_run_id_erp_sync_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_customers')),
    sa.UniqueConstraint('erp_name', name=op.f('uq_erp_customers_erp_name'))
    )
    op.create_table('erp_grades',
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('company_normalized', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=128), nullable=False),
    sa.Column('grade_normalized', sa.String(length=128), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=True),
    sa.Column('erp_sr_no', sa.Integer(), nullable=True),
    sa.Column('mfi', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('density', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('erp_item_code', sa.String(length=64), nullable=True),
    sa.Column('producer_id', sa.Uuid(), nullable=True),
    sa.Column('producer_grade_alias_id', sa.Uuid(), nullable=True),
    sa.Column('mapping_status', sa.String(length=24), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("mapping_status IN ('mapped', 'unmapped_producer', 'unmapped_grade')", name=op.f('ck_erp_grades_mapping_status')),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['erp_sync_runs.id'], name=op.f('fk_erp_grades_last_sync_run_id_erp_sync_runs')),
    sa.ForeignKeyConstraint(['producer_grade_alias_id'], ['producer_grade_aliases.id'], name=op.f('fk_erp_grades_producer_grade_alias_id_producer_grade_aliases')),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_erp_grades_producer_id_producers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_grades')),
    sa.UniqueConstraint('company_normalized', 'grade_normalized', name='uq_erp_grades_identity')
    )
    op.create_table('erp_price_row_imports',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('erp_sys_date', sa.DateTime(), nullable=False),
    sa.Column('erp_sr_no', sa.Integer(), nullable=False),
    sa.Column('source_rate_id', sa.Uuid(), nullable=False),
    sa.Column('sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['rate_sources.id'], name=op.f('fk_erp_price_row_imports_source_id_rate_sources')),
    sa.ForeignKeyConstraint(['source_rate_id'], ['source_rates.id'], name=op.f('fk_erp_price_row_imports_source_rate_id_source_rates')),
    sa.ForeignKeyConstraint(['sync_run_id'], ['erp_sync_runs.id'], name=op.f('fk_erp_price_row_imports_sync_run_id_erp_sync_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_price_row_imports')),
    sa.UniqueConstraint('source_id', 'erp_sys_date', 'erp_sr_no', name='uq_erp_price_row_imports_identity'),
    sa.UniqueConstraint('source_rate_id', name=op.f('uq_erp_price_row_imports_source_rate_id'))
    )
    op.create_index(op.f('ix_erp_price_row_imports_sync_run_id'), 'erp_price_row_imports', ['sync_run_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(LEDGER_IMMUTABLE)
    for code, description in PERMISSIONS:
        op.execute(
            f"INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), '{code}', '{description}')"
        )
    for role in ERP_SYNC_ROLES:
        op.execute(
            "INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p WHERE r.code = '{role}' AND p.code = 'integration.erp.sync'"
        )


PERMISSIONS = [("integration.erp.sync", "Run the read-only ERP import into SourceOne")]
ERP_SYNC_ROLES = ("platform_admin", "pricing_admin")

LEDGER_IMMUTABLE = """
CREATE FUNCTION erp_price_row_imports_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'imported ERP row % is immutable', OLD.id USING ERRCODE = 'check_violation';
END $$;
CREATE TRIGGER erp_price_row_imports_immutable BEFORE UPDATE OR DELETE ON erp_price_row_imports
    FOR EACH ROW EXECUTE FUNCTION erp_price_row_imports_immutable();
"""


def downgrade() -> None:
    """Downgrade schema."""
    codes = ", ".join(f"'{code}'" for code, _ in PERMISSIONS)
    op.execute(f"DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN ({codes}))")
    op.execute(f"DELETE FROM permissions WHERE code IN ({codes})")
    op.execute("DROP TRIGGER erp_price_row_imports_immutable ON erp_price_row_imports")
    op.execute("DROP FUNCTION erp_price_row_imports_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_price_row_imports_sync_run_id'), table_name='erp_price_row_imports')
    op.drop_table('erp_price_row_imports')
    op.drop_table('erp_grades')
    op.drop_table('erp_customers')
    op.drop_table('erp_sync_runs')
    # ### end Alembic commands ###
