"""order v1

Revision ID: 3f30832047e2
Revises: 8628f80ec2a6
Create Date: 2026-09-28 16:36:50.462475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f30832047e2'
down_revision: Union[str, Sequence[str], None] = '8628f80ec2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


INSERT_GUARD = """
CREATE FUNCTION orders_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    n negotiations%ROWTYPE;
    v negotiation_versions%ROWTYPE;
BEGIN
    SELECT * INTO n FROM negotiations WHERE id = NEW.negotiation_id;
    IF n.status <> 'accepted' OR n.accepted_version_id IS DISTINCT FROM NEW.negotiation_version_id THEN
        RAISE EXCEPTION 'orders can only be placed from the accepted version of an accepted negotiation'
            USING ERRCODE = 'check_violation';
    END IF;
    SELECT * INTO v FROM negotiation_versions WHERE id = NEW.negotiation_version_id;
    IF (NEW.buyer_user_id, NEW.supplier_user_id, NEW.product_id, NEW.quantity, NEW.uom, NEW.currency,
        NEW.agreed_unit_price)
       IS DISTINCT FROM (n.buyer_user_id, n.supplier_user_id, n.product_id, v.quantity, v.uom, v.currency,
        v.offered_price) THEN
        RAISE EXCEPTION 'order terms must equal the accepted negotiation version' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.status <> 'placed' THEN
        RAISE EXCEPTION 'new orders start as placed' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER orders_insert_guard BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION orders_insert_guard();
"""

UPDATE_GUARD = """
CREATE FUNCTION orders_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'order % cannot be deleted', OLD.id USING ERRCODE = 'check_violation';
    END IF;
    IF OLD.status IN ('delivered', 'cancelled') THEN
        RAISE EXCEPTION 'order % is % and is final', OLD.id, OLD.status USING ERRCODE = 'check_violation';
    END IF;
    IF (NEW.order_number, NEW.negotiation_id, NEW.negotiation_version_id, NEW.buyer_user_id, NEW.supplier_user_id,
        NEW.product_id, NEW.quantity, NEW.uom, NEW.currency, NEW.agreed_unit_price, NEW.total_value, NEW.created_at)
       IS DISTINCT FROM
       (OLD.order_number, OLD.negotiation_id, OLD.negotiation_version_id, OLD.buyer_user_id, OLD.supplier_user_id,
        OLD.product_id, OLD.quantity, OLD.uom, OLD.currency, OLD.agreed_unit_price, OLD.total_value, OLD.created_at) THEN
        RAISE EXCEPTION 'order % terms are immutable', OLD.id USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
        (OLD.status = 'placed' AND NEW.status IN ('confirmed', 'cancelled')) OR
        (OLD.status = 'confirmed' AND NEW.status IN ('processing', 'cancelled')) OR
        (OLD.status = 'processing' AND NEW.status = 'ready') OR
        (OLD.status = 'ready' AND NEW.status = 'dispatched') OR
        (OLD.status = 'dispatched' AND NEW.status = 'delivered')
    ) THEN
        RAISE EXCEPTION 'order % cannot move from % to %', OLD.id, OLD.status, NEW.status
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER orders_guard BEFORE UPDATE OR DELETE ON orders FOR EACH ROW EXECUTE FUNCTION orders_guard();
"""

PERMISSIONS = [
    ("order.place", "Place and cancel own orders from accepted negotiations"),
    ("order.fulfil", "View, progress and cancel assigned orders as the supplier"),
]
ROLE_PERMISSIONS = {"buyer": "order.place", "supplier": "order.fulfil"}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('negotiation_id', sa.Uuid(), nullable=False),
    sa.Column('negotiation_version_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_user_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('agreed_unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'cancelled') = (cancelled_at IS NOT NULL)", name=op.f('ck_orders_cancelled_iff_cancelled_at')),
    sa.CheckConstraint("currency IN ('INR', 'USD')", name=op.f('ck_orders_currency')),
    sa.CheckConstraint("status IN ('placed', 'confirmed', 'processing', 'ready', 'dispatched', 'delivered', 'cancelled')", name=op.f('ck_orders_status')),
    sa.CheckConstraint("uom IN ('KG')", name=op.f('ck_orders_uom')),
    sa.CheckConstraint('agreed_unit_price > 0', name=op.f('ck_orders_agreed_unit_price_positive')),
    sa.CheckConstraint('buyer_user_id <> supplier_user_id', name=op.f('ck_orders_distinct_parties')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('total_value = round(quantity * agreed_unit_price, 2)', name=op.f('ck_orders_total_matches_terms')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_orders_buyer_user_id_users')),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_orders_cancelled_by_user_id_users')),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], name=op.f('fk_orders_negotiation_id_negotiations')),
    sa.ForeignKeyConstraint(['negotiation_version_id'], ['negotiation_versions.id'], name=op.f('fk_orders_negotiation_version_id_negotiation_versions')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_user_id'], ['users.id'], name=op.f('fk_orders_supplier_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('negotiation_id', name=op.f('uq_orders_negotiation_id')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index('ix_orders_buyer_status', 'orders', ['buyer_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index('ix_orders_supplier_status', 'orders', ['supplier_user_id', 'status'], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE SEQUENCE order_number_seq OWNED BY orders.order_number")
    op.execute(INSERT_GUARD)
    op.execute(UPDATE_GUARD)
    for code, description in PERMISSIONS:
        op.execute(
            f"INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), '{code}', '{description}')"
        )
    for role, permission in ROLE_PERMISSIONS.items():
        op.execute(
            "INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p WHERE r.code = '{role}' AND p.code = '{permission}'"
        )


def downgrade() -> None:
    """Downgrade schema."""
    codes = ", ".join(f"'{code}'" for code, _ in PERMISSIONS)
    op.execute(f"DELETE FROM permissions WHERE code IN ({codes})")
    op.execute("DROP TRIGGER orders_guard ON orders")
    op.execute("DROP FUNCTION orders_guard()")
    op.execute("DROP TRIGGER orders_insert_guard ON orders")
    op.execute("DROP FUNCTION orders_insert_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_supplier_status', table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index('ix_orders_buyer_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
