"""erp grade identity includes quality

Revision ID: 410fac54e2de
Revises: 3c741306f4ca
Create Date: 2026-09-29 10:55:15.222448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410fac54e2de'
down_revision: Union[str, Sequence[str], None] = '3c741306f4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erp_grades', sa.Column('quality_normalized', sa.String(length=64), server_default='', nullable=False))
    op.drop_constraint(op.f('uq_erp_grades_identity'), 'erp_grades', type_='unique')
    op.create_unique_constraint('uq_erp_grades_identity', 'erp_grades', ['company_normalized', 'quality_normalized', 'grade_normalized'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_erp_grades_identity', 'erp_grades', type_='unique')
    op.create_unique_constraint(op.f('uq_erp_grades_identity'), 'erp_grades', ['company_normalized', 'grade_normalized'], postgresql_nulls_not_distinct=False)
    op.drop_column('erp_grades', 'quality_normalized')
    # ### end Alembic commands ###
