"""order tracking v1

Revision ID: 720924656e23
Revises: 3f30832047e2
Create Date: 2026-09-28 16:45:08.379019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720924656e23'
down_revision: Union[str, Sequence[str], None] = '3f30832047e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_events',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(from_status IS NULL) = (to_status = 'placed')", name=op.f('ck_order_status_events_placed_is_first')),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('placed', 'confirmed', 'processing', 'ready', 'dispatched', 'delivered', 'cancelled')", name=op.f('ck_order_status_events_from_status')),
    sa.CheckConstraint("to_status IN ('placed', 'confirmed', 'processing', 'ready', 'dispatched', 'delivered', 'cancelled')", name=op.f('ck_order_status_events_to_status')),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_order_status_events_changed_by_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_events_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_events')),
    sa.UniqueConstraint('order_id', 'to_status', name='uq_order_status_events_order_to_status')
    )
    op.create_index('ix_order_status_events_order_created', 'order_status_events', ['order_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(BACKFILL)
    op.execute(EVENT_GUARDS)
    op.execute(ORDER_HAS_EVENT)


BACKFILL = """
WITH flow(status, pos) AS (
    VALUES ('placed', 1), ('confirmed', 2), ('processing', 3), ('ready', 4), ('dispatched', 5), ('delivered', 6)
), steps AS (
    SELECT o.id AS order_id, f.status, f.pos, o.buyer_user_id, o.supplier_user_id, o.created_at, o.updated_at
    FROM orders o
    JOIN flow f ON f.pos <= COALESCE((SELECT pos FROM flow WHERE flow.status = o.status), 1)
)
INSERT INTO order_status_events (id, order_id, from_status, to_status, changed_by_user_id, note, created_at)
SELECT gen_random_uuid(), order_id,
       lag(status) OVER (PARTITION BY order_id ORDER BY pos), status,
       CASE WHEN status = 'placed' THEN buyer_user_id ELSE supplier_user_id END,
       NULL,
       CASE WHEN status = 'placed' THEN created_at ELSE updated_at END
FROM steps;

INSERT INTO order_status_events (id, order_id, from_status, to_status, changed_by_user_id, note, created_at)
SELECT gen_random_uuid(), id, 'placed', 'cancelled', COALESCE(cancelled_by_user_id, buyer_user_id),
       cancel_reason, COALESCE(cancelled_at, updated_at)
FROM orders WHERE status = 'cancelled';
"""

EVENT_GUARDS = """
CREATE FUNCTION order_status_events_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'order status event % is immutable', OLD.id USING ERRCODE = 'check_violation';
END $$;
CREATE TRIGGER order_status_events_immutable BEFORE UPDATE OR DELETE ON order_status_events
    FOR EACH ROW EXECUTE FUNCTION order_status_events_immutable();

CREATE FUNCTION order_status_events_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    current_status text;
    tip order_status_events%ROWTYPE;
BEGIN
    SELECT status INTO current_status FROM orders WHERE id = NEW.order_id;
    IF current_status IS DISTINCT FROM NEW.to_status THEN
        RAISE EXCEPTION 'status event must record the order''s current status (%), not %', current_status, NEW.to_status
            USING ERRCODE = 'check_violation';
    END IF;
    SELECT e.* INTO tip FROM order_status_events e
    WHERE e.order_id = NEW.order_id
      AND NOT EXISTS (
          SELECT 1 FROM order_status_events n WHERE n.order_id = e.order_id AND n.from_status = e.to_status
      );
    IF NEW.from_status IS DISTINCT FROM tip.to_status THEN
        RAISE EXCEPTION 'status event must continue from %, not %', tip.to_status, NEW.from_status
            USING ERRCODE = 'check_violation';
    END IF;
    IF tip.created_at IS NOT NULL AND NEW.created_at < tip.created_at THEN
        RAISE EXCEPTION 'status event cannot predate the previous event' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER order_status_events_insert_guard BEFORE INSERT ON order_status_events
    FOR EACH ROW EXECUTE FUNCTION order_status_events_insert_guard();
"""

ORDER_HAS_EVENT = """
CREATE FUNCTION orders_status_has_event() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM order_status_events WHERE order_id = NEW.id AND to_status = NEW.status
    ) THEN
        RAISE EXCEPTION 'order % reached % without a status event', NEW.id, NEW.status USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER orders_status_has_event AFTER INSERT OR UPDATE OF status ON orders
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION orders_status_has_event();
"""


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER orders_status_has_event ON orders")
    op.execute("DROP FUNCTION orders_status_has_event()")
    op.execute("DROP TRIGGER order_status_events_insert_guard ON order_status_events")
    op.execute("DROP FUNCTION order_status_events_insert_guard()")
    op.execute("DROP TRIGGER order_status_events_immutable ON order_status_events")
    op.execute("DROP FUNCTION order_status_events_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_status_events_order_created', table_name='order_status_events')
    op.drop_table('order_status_events')
    # ### end Alembic commands ###
