"""purchase requests

Revision ID: 9c8b6c2e0d63
Revises: 52366dff2096
Create Date: 2026-09-29 12:32:27.140526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8b6c2e0d63'
down_revision: Union[str, Sequence[str], None] = '52366dff2096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requests',
    sa.Column('request_number', sa.String(length=32), nullable=False),
    sa.Column('buyer_user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('destination_pin', sa.String(length=6), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'cancelled') = (cancelled_at IS NOT NULL)", name=op.f('ck_purchase_requests_cancelled_iff_cancelled_at')),
    sa.CheckConstraint("destination_pin ~ '^[1-9][0-9]{5}$'", name=op.f('ck_purchase_requests_destination_pin')),
    sa.CheckConstraint("status IN ('draft', 'sent', 'in_negotiation', 'converted', 'cancelled')", name=op.f('ck_purchase_requests_status')),
    sa.CheckConstraint("uom IN ('KG')", name=op.f('ck_purchase_requests_uom')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_requests_quantity_positive')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_purchase_requests_buyer_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_requests_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requests')),
    sa.UniqueConstraint('request_number', name=op.f('uq_purchase_requests_request_number'))
    )
    op.create_index('ix_purchase_requests_buyer_status', 'purchase_requests', ['buyer_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_requests_product_id'), 'purchase_requests', ['product_id'], unique=False)
    op.create_table('purchase_request_suppliers',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_user_id', sa.Uuid(), nullable=False),
    sa.Column('negotiation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], name=op.f('fk_purchase_request_suppliers_negotiation_id_negotiations')),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.id'], name=op.f('fk_purchase_request_suppliers_request_id_purchase_requests')),
    sa.ForeignKeyConstraint(['supplier_user_id'], ['users.id'], name=op.f('fk_purchase_request_suppliers_supplier_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_request_suppliers')),
    sa.UniqueConstraint('negotiation_id', name=op.f('uq_purchase_request_suppliers_negotiation_id')),
    sa.UniqueConstraint('request_id', 'supplier_user_id', name='uq_purchase_request_suppliers_request_supplier')
    )
    op.create_index('ix_purchase_request_suppliers_supplier', 'purchase_request_suppliers', ['supplier_user_id'], unique=False)
    op.execute("CREATE SEQUENCE purchase_request_number_seq OWNED BY purchase_requests.request_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE IF EXISTS purchase_request_number_seq")
    op.drop_index('ix_purchase_request_suppliers_supplier', table_name='purchase_request_suppliers')
    op.drop_table('purchase_request_suppliers')
    op.drop_index(op.f('ix_purchase_requests_product_id'), table_name='purchase_requests')
    op.drop_index('ix_purchase_requests_buyer_status', table_name='purchase_requests')
    op.drop_table('purchase_requests')
    # ### end Alembic commands ###
