"""supplier listings

Revision ID: bafc7b2e3678
Revises: e1df2d924085
Create Date: 2026-09-29 11:21:05.626256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafc7b2e3678'
down_revision: Union[str, Sequence[str], None] = 'e1df2d924085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_listings',
    sa.Column('supplier_user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('minimum_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability IN ('in_stock', 'limited', 'on_request')", name=op.f('ck_supplier_listings_availability')),
    sa.CheckConstraint("currency IN ('INR', 'USD')", name=op.f('ck_supplier_listings_currency')),
    sa.CheckConstraint("uom IN ('KG')", name=op.f('ck_supplier_listings_uom')),
    sa.CheckConstraint('asking_price > 0', name=op.f('ck_supplier_listings_asking_price_positive')),
    sa.CheckConstraint('minimum_quantity > 0', name=op.f('ck_supplier_listings_minimum_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_listings_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_user_id'], ['users.id'], name=op.f('fk_supplier_listings_supplier_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_listings')),
    sa.UniqueConstraint('supplier_user_id', 'product_id', name='uq_supplier_listings_supplier_product')
    )
    op.create_index(op.f('ix_supplier_listings_product_id'), 'supplier_listings', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_listings_supplier_user_id'), 'supplier_listings', ['supplier_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_listings_supplier_user_id'), table_name='supplier_listings')
    op.drop_index(op.f('ix_supplier_listings_product_id'), table_name='supplier_listings')
    op.drop_table('supplier_listings')
    # ### end Alembic commands ###
