"""product catalogue

Revision ID: c1be8c1da225
Revises: a7c3e9d21f04
Create Date: 2026-09-28 16:16:10.460453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1be8c1da225'
down_revision: Union[str, Sequence[str], None] = 'a7c3e9d21f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('product_code', name=op.f('uq_products_product_code'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('product_rate_series',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('rate_series_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_rate_series_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_series_id'], ['rate_series.id'], name=op.f('fk_product_rate_series_rate_series_id_rate_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_rate_series')),
    sa.UniqueConstraint('product_id', 'rate_series_id', name='uq_product_rate_series_pair')
    )
    op.create_index(op.f('ix_product_rate_series_rate_series_id'), 'product_rate_series', ['rate_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_rate_series_rate_series_id'), table_name='product_rate_series')
    op.drop_table('product_rate_series')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
