"""identity catalogue pricing v1

Revision ID: cefda1eeff3e
Revises: 
Create Date: 2026-09-28 15:22:01.148181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cefda1eeff3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('polymer', sa.String(length=32), nullable=False),
    sa.Column('application', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('code', name=op.f('uq_grades_code'))
    )
    op.create_table('markets',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("market_type IN ('domestic', 'import_origin')", name=op.f('ck_markets_market_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('code', name=op.f('uq_markets_code'))
    )
    op.create_table('organisations',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("org_type IN ('platform', 'buyer', 'supplier')", name=op.f('ck_organisations_org_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations')),
    sa.UniqueConstraint('code', name=op.f('uq_organisations_code'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('producers',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producers')),
    sa.UniqueConstraint('code', name=op.f('uq_producers_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('grade_equivalence',
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.Column('producer_grade_code', sa.String(length=64), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_grade_equivalence_grade_id_grades')),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_grade_equivalence_producer_id_producers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_equivalence')),
    sa.UniqueConstraint('producer_id', 'producer_grade_code', name=op.f('uq_grade_equivalence_producer_id'))
    )
    op.create_index(op.f('ix_grade_equivalence_grade_id'), 'grade_equivalence', ['grade_id'], unique=False)
    op.create_table('market_aliases',
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('alias_normalized', sa.String(length=128), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_aliases_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_aliases')),
    sa.UniqueConstraint('alias_normalized', name=op.f('uq_market_aliases_alias_normalized'))
    )
    op.create_index(op.f('ix_market_aliases_market_id'), 'market_aliases', ['market_id'], unique=False)
    op.create_table('producer_grade_aliases',
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('alias_normalized', sa.String(length=128), nullable=False),
    sa.Column('producer_grade_code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_producer_grade_aliases_producer_id_producers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producer_grade_aliases')),
    sa.UniqueConstraint('producer_id', 'alias_normalized', name=op.f('uq_producer_grade_aliases_producer_id'))
    )
    op.create_table('rate_series',
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('price_basis', sa.String(length=32), nullable=False),
    sa.Column('tax_basis', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IN ('INR', 'USD')", name=op.f('ck_rate_series_currency')),
    sa.CheckConstraint("unit IN ('KG')", name=op.f('ck_rate_series_unit')),
    sa.CheckConstraint("visibility IN ('signed_in_platform')", name=op.f('ck_rate_series_visibility')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_rate_series_grade_id_grades')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_rate_series_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_series')),
    sa.UniqueConstraint('code', name=op.f('uq_rate_series_code')),
    sa.UniqueConstraint('grade_id', 'market_id', 'price_basis', 'tax_basis', 'currency', 'unit', name='uq_rate_series_definition')
    )
    op.create_index(op.f('ix_rate_series_market_id'), 'rate_series', ['market_id'], unique=False)
    op.create_table('rate_sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('staleness_days', sa.Integer(), nullable=False),
    sa.Column('publishing_policy', sa.String(length=32), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('default_unit', sa.String(length=16), nullable=True),
    sa.Column('normalization_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('profile_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('owner_organisation_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("publishing_policy IN ('review_required')", name=op.f('ck_rate_sources_publishing_policy')),
    sa.CheckConstraint("source_type IN ('erp_feed', 'manual', 'external_api', 'supplier_submission')", name=op.f('ck_rate_sources_source_type')),
    sa.CheckConstraint('staleness_days > 0', name=op.f('ck_rate_sources_staleness_days_positive')),
    sa.ForeignKeyConstraint(['owner_organisation_id'], ['organisations.id'], name=op.f('fk_rate_sources_owner_organisation_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_rate_sources_code'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_users_organisation_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('benchmark_rates',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('primary_source_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('price_basis', sa.String(length=32), nullable=False),
    sa.Column('tax_basis', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('four_eyes_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_as_of_date', sa.Date(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staleness_days', sa.Integer(), nullable=True),
    sa.Column('stale_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_edited_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_id', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('withdrawn_by_id', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_reason', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("currency IN ('INR', 'USD')", name=op.f('ck_benchmark_rates_currency')),
    sa.CheckConstraint("method <> 'manual' OR (reason IS NOT NULL AND length(trim(reason)) > 0)", name=op.f('ck_benchmark_rates_manual_requires_reason')),
    sa.CheckConstraint("method IN ('adopted', 'manual', 'aggregated')", name=op.f('ck_benchmark_rates_method')),
    sa.CheckConstraint("origin IN ('system_suggestion', 'human')", name=op.f('ck_benchmark_rates_origin')),
    sa.CheckConstraint("status <> 'rejected' OR (rejected_at IS NOT NULL AND rejected_by_id IS NOT NULL AND rejected_reason IS NOT NULL)", name=op.f('ck_benchmark_rates_rejected_is_complete')),
    sa.CheckConstraint("status <> 'withdrawn' OR (withdrawn_at IS NOT NULL AND withdrawn_by_id IS NOT NULL AND withdrawn_reason IS NOT NULL)", name=op.f('ck_benchmark_rates_withdrawn_is_complete')),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'published', 'rejected', 'withdrawn')", name=op.f('ck_benchmark_rates_status')),
    sa.CheckConstraint("status NOT IN ('published', 'withdrawn') OR (published_at IS NOT NULL AND published_by_id IS NOT NULL AND stale_after IS NOT NULL AND staleness_days IS NOT NULL)", name=op.f('ck_benchmark_rates_published_is_complete')),
    sa.CheckConstraint("unit IN ('KG')", name=op.f('ck_benchmark_rates_unit')),
    sa.CheckConstraint('effective_until IS NULL OR effective_until > effective_from', name=op.f('ck_benchmark_rates_effective_window')),
    sa.CheckConstraint('value > 0', name=op.f('ck_benchmark_rates_value_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_created_by_id_users')),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_last_edited_by_id_users')),
    sa.ForeignKeyConstraint(['primary_source_id'], ['rate_sources.id'], name=op.f('fk_benchmark_rates_primary_source_id_rate_sources')),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_published_by_id_users')),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_rejected_by_id_users')),
    sa.ForeignKeyConstraint(['series_id'], ['rate_series.id'], name=op.f('fk_benchmark_rates_series_id_rate_series')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_submitted_by_id_users')),
    sa.ForeignKeyConstraint(['withdrawn_by_id'], ['users.id'], name=op.f('fk_benchmark_rates_withdrawn_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_rates'))
    )
    op.create_index('ix_benchmark_rates_series_status', 'benchmark_rates', ['series_id', 'status'], unique=False)
    op.create_index('uq_benchmark_rates_series_effective_from', 'benchmark_rates', ['series_id', 'effective_from'], unique=True, postgresql_where=sa.text("status IN ('published', 'withdrawn')"))
    op.create_table('import_batches',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_as_of_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unresolved_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ineligible_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_import_batches_status')),
    sa.ForeignKeyConstraint(['source_id'], ['rate_sources.id'], name=op.f('fk_import_batches_source_id_rate_sources')),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_import_batches_triggered_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('source_id', 'source_as_of_date', 'checksum', name='uq_import_batches_source_date_checksum')
    )
    op.create_index(op.f('ix_import_batches_source_id'), 'import_batches', ['source_id'], unique=False)
    op.create_table('pricing_audit_events',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_pricing_audit_events_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_audit_events'))
    )
    op.create_index('ix_pricing_audit_events_entity', 'pricing_audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_user_roles_assigned_by_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('source_rates',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=128), nullable=False),
    sa.Column('source_row_key', sa.String(length=128), nullable=False),
    sa.Column('source_identity_key', sa.String(length=128), nullable=False),
    sa.Column('source_as_of_date', sa.Date(), nullable=False),
    sa.Column('raw_producer', sa.String(length=255), nullable=True),
    sa.Column('raw_grade', sa.String(length=255), nullable=True),
    sa.Column('raw_location', sa.String(length=255), nullable=True),
    sa.Column('raw_sector', sa.String(length=64), nullable=True),
    sa.Column('origin_location', sa.String(length=255), nullable=True),
    sa.Column('application', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=16), nullable=True),
    sa.Column('producer_id', sa.Uuid(), nullable=True),
    sa.Column('grade_id', sa.Uuid(), nullable=True),
    sa.Column('market_id', sa.Uuid(), nullable=True),
    sa.Column('series_id', sa.Uuid(), nullable=True),
    sa.Column('producer_grade_alias_id', sa.Uuid(), nullable=True),
    sa.Column('grade_equivalence_id', sa.Uuid(), nullable=True),
    sa.Column('market_alias_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('price_basis', sa.String(length=32), nullable=True),
    sa.Column('tax_basis', sa.String(length=32), nullable=True),
    sa.Column('resolution_status', sa.String(length=16), nullable=False),
    sa.Column('resolution_reason', sa.String(length=64), nullable=True),
    sa.Column('is_benchmark_eligible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('eligibility_reason', sa.String(length=64), nullable=True),
    sa.Column('is_unchanged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_profile_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("NOT is_benchmark_eligible OR (resolution_status = 'resolved' AND series_id IS NOT NULL)", name=op.f('ck_source_rates_eligible_requires_series')),
    sa.CheckConstraint("resolution_status <> 'resolved' OR (value IS NOT NULL AND currency IS NOT NULL AND unit IS NOT NULL AND grade_id IS NOT NULL AND market_id IS NOT NULL)", name=op.f('ck_source_rates_resolved_is_complete')),
    sa.CheckConstraint("resolution_status IN ('resolved', 'unresolved', 'ignored')", name=op.f('ck_source_rates_resolution_status')),
    sa.CheckConstraint("sector IS NULL OR sector IN ('DOMESTIC', 'DEEMED', 'IMPORT')", name=op.f('ck_source_rates_sector')),
    sa.CheckConstraint('value IS NULL OR value > 0', name=op.f('ck_source_rates_value_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_source_rates_created_by_id_users')),
    sa.ForeignKeyConstraint(['grade_equivalence_id'], ['grade_equivalence.id'], name=op.f('fk_source_rates_grade_equivalence_id_grade_equivalence')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_source_rates_grade_id_grades')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_source_rates_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['market_alias_id'], ['market_aliases.id'], name=op.f('fk_source_rates_market_alias_id_market_aliases')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_source_rates_market_id_markets')),
    sa.ForeignKeyConstraint(['producer_grade_alias_id'], ['producer_grade_aliases.id'], name=op.f('fk_source_rates_producer_grade_alias_id_producer_grade_aliases')),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], name=op.f('fk_source_rates_producer_id_producers')),
    sa.ForeignKeyConstraint(['series_id'], ['rate_series.id'], name=op.f('fk_source_rates_series_id_rate_series')),
    sa.ForeignKeyConstraint(['source_id'], ['rate_sources.id'], name=op.f('fk_source_rates_source_id_rate_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_rates')),
    sa.UniqueConstraint('import_batch_id', 'source_row_key', name='uq_source_rates_batch_row_key')
    )
    op.create_index('ix_source_rates_identity', 'source_rates', ['source_id', 'source_identity_key', 'source_as_of_date'], unique=False)
    op.create_index('ix_source_rates_series_as_of', 'source_rates', ['series_id', 'source_as_of_date'], unique=False)
    op.create_table('benchmark_rate_inputs',
    sa.Column('benchmark_rate_id', sa.Uuid(), nullable=False),
    sa.Column('source_rate_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'supporting')", name=op.f('ck_benchmark_rate_inputs_role')),
    sa.ForeignKeyConstraint(['benchmark_rate_id'], ['benchmark_rates.id'], name=op.f('fk_benchmark_rate_inputs_benchmark_rate_id_benchmark_rates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_rate_id'], ['source_rates.id'], name=op.f('fk_benchmark_rate_inputs_source_rate_id_source_rates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_rate_inputs')),
    sa.UniqueConstraint('benchmark_rate_id', 'source_rate_id', name='uq_benchmark_rate_inputs_pair')
    )
    op.create_index(op.f('ix_benchmark_rate_inputs_source_rate_id'), 'benchmark_rate_inputs', ['source_rate_id'], unique=False)
    op.create_index('uq_benchmark_rate_inputs_one_primary', 'benchmark_rate_inputs', ['benchmark_rate_id'], unique=True, postgresql_where=sa.text("role = 'primary'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_benchmark_rate_inputs_one_primary', table_name='benchmark_rate_inputs', postgresql_where=sa.text("role = 'primary'"))
    op.drop_index(op.f('ix_benchmark_rate_inputs_source_rate_id'), table_name='benchmark_rate_inputs')
    op.drop_table('benchmark_rate_inputs')
    op.drop_index('ix_source_rates_series_as_of', table_name='source_rates')
    op.drop_index('ix_source_rates_identity', table_name='source_rates')
    op.drop_table('source_rates')
    op.drop_table('user_roles')
    op.drop_index('ix_pricing_audit_events_entity', table_name='pricing_audit_events')
    op.drop_table('pricing_audit_events')
    op.drop_index(op.f('ix_import_batches_source_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('uq_benchmark_rates_series_effective_from', table_name='benchmark_rates', postgresql_where=sa.text("status IN ('published', 'withdrawn')"))
    op.drop_index('ix_benchmark_rates_series_status', table_name='benchmark_rates')
    op.drop_table('benchmark_rates')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('rate_sources')
    op.drop_index(op.f('ix_rate_series_market_id'), table_name='rate_series')
    op.drop_table('rate_series')
    op.drop_table('producer_grade_aliases')
    op.drop_index(op.f('ix_market_aliases_market_id'), table_name='market_aliases')
    op.drop_table('market_aliases')
    op.drop_index(op.f('ix_grade_equivalence_grade_id'), table_name='grade_equivalence')
    op.drop_table('grade_equivalence')
    op.drop_table('roles')
    op.drop_table('producers')
    op.drop_table('permissions')
    op.drop_table('organisations')
    op.drop_table('markets')
    op.drop_table('grades')
    # ### end Alembic commands ###
