"""product documents and questions

Revision ID: f46af178675f
Revises: 9c8b6c2e0d63
Create Date: 2026-09-29 12:40:41.052920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46af178675f'
down_revision: Union[str, Sequence[str], None] = '9c8b6c2e0d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_documents',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('stored_name', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_documents_product_id_products')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_product_documents_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_documents')),
    sa.UniqueConstraint('stored_name', name=op.f('uq_product_documents_stored_name'))
    )
    op.create_index('ix_product_documents_product', 'product_documents', ['product_id'], unique=False)
    op.create_table('product_questions',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'answered')", name=op.f('ck_product_questions_status')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_product_questions_buyer_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_questions_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_questions'))
    )
    op.create_index('ix_product_questions_product', 'product_questions', ['product_id'], unique=False)
    op.create_table('product_answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['product_questions.id'], name=op.f('fk_product_answers_question_id_product_questions')),
    sa.ForeignKeyConstraint(['supplier_user_id'], ['users.id'], name=op.f('fk_product_answers_supplier_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_answers'))
    )
    op.create_index(op.f('ix_product_answers_question_id'), 'product_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_answers_question_id'), table_name='product_answers')
    op.drop_table('product_answers')
    op.drop_index('ix_product_questions_product', table_name='product_questions')
    op.drop_table('product_questions')
    op.drop_index('ix_product_documents_product', table_name='product_documents')
    op.drop_table('product_documents')
    # ### end Alembic commands ###
